version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - JMS_network
  
  mongodb-container:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
    networks:
        - JMS_network
  
  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6379:6379
    volumes:
      - redisData:/data
    networks:
      - JMS_network
  

  elastic:
    image: elasticsearch:7.17.14
    container_name: 'elasticsearch'
    ports:
      - 9200:9200
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'root'
    networks:
      - JMS_network
  

  kibana:
    image: kibana:7.17.14
    container_name: 'kibana'
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://localhost:9200/
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=root
    networks:
      - JMS_network


    


networks:
  JMS_network:
  
volumes:
  mongoData:
  redisData:
  elasticData:
  


